// src/routes/dashboard/+page.svelte
<script lang="ts">
    import { page } from '$app/stores';
    import { Home, Database, FileText, Layout, Users, Settings, MessageSquare } from 'lucide-svelte';
    
    // Demo stats data
    const stats = [
        { title: 'Total Pages', count: 24, icon: Layout, change: '+12%', color: 'bg-blue-500' },
        { title: 'Total Posts', count: 128, icon: FileText, change: '+5%', color: 'bg-green-500' },
        { title: 'Active Users', count: 38, icon: Users, change: '+8%', color: 'bg-purple-500' },
        { title: 'Mini Apps', count: 12, icon: Database, change: '+2%', color: 'bg-amber-500' }
    ];
    
    // Recent activity
    const activity = [
        { type: 'edit', item: 'Homepage', user: 'John Doe', time: '5 minutes ago' },
        { type: 'create', item: 'New Blog Post', user: 'Jane Smith', time: '1 hour ago' },
        { type: 'comment', item: 'Product Review', user: 'Alice Johnson', time: '3 hours ago' },
        { type: 'settings', item: 'System Settings', user: 'Admin', time: '1 day ago' },
        { type: 'upload', item: 'New Media Files', user: 'Bob Martin', time: '2 days ago' }
    ];
</script>

<div class="container mx-auto p-6">
    <div class="flex justify-between items-center mb-8">
        <h1 class="text-3xl font-bold">Dashboard</h1>
        <div class="flex gap-2">
            <button class="btn btn-outline btn-sm">Export</button>
            <button class="btn btn-primary btn-sm">New Item</button>
        </div>
    </div>
    
    <!-- Stats grid -->
    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 mb-8">
        {#each stats as stat}
            <div class="bg-card rounded-lg shadow p-6 flex items-center space-x-4">
                <div class="flex-shrink-0">
                    <div class="p-3 rounded-full {stat.color} text-white">
                        <svelte:component this={stat.icon} size={24} />
                    </div>
                </div>
                <div>
                    <p class="text-sm text-muted-foreground">{stat.title}</p>
                    <div class="flex items-baseline space-x-2">
                        <h3 class="text-2xl font-bold">{stat.count}</h3>
                        <span class="text-xs font-semibold text-green-500">{stat.change}</span>
                    </div>
                </div>
            </div>
        {/each}
    </div>
    
    <div class="grid grid-cols-1 lg:grid-cols-3 gap-6">
        <!-- Main chart section -->
        <div class="bg-card rounded-lg shadow p-6 lg:col-span-2">
            <h2 class="text-xl font-semibold mb-4">Activity Overview</h2>
            <!-- Placeholder for chart -->
            <div class="h-[300px] bg-muted/20 rounded flex items-center justify-center">
                <p class="text-muted-foreground">Activity Chart Placeholder</p>
            </div>
        </div>
        
        <!-- Recent activity section -->
        <div class="bg-card rounded-lg shadow p-6">
            <h2 class="text-xl font-semibold mb-4">Recent Activity</h2>
            <div class="space-y-4">
                {#each activity as item}
                    <div class="flex items-start space-x-3 pb-3 border-b last:border-0">
                        <div class="p-2 rounded-full bg-muted">
                            <svelte:component this={
                                item.type === 'edit' ? FileText :
                                item.type === 'create' ? Layout :
                                item.type === 'comment' ? MessageSquare :
                                item.type === 'settings' ? Settings :
                                Home
                            } size={16} />
                        </div>
                        <div>
                            <p class="text-sm font-medium">{item.item}</p>
                            <div class="text-xs text-muted-foreground flex items-center gap-2">
                                <span>{item.user}</span>
                                <span class="inline-block w-1 h-1 rounded-full bg-muted-foreground"></span>
                                <span>{item.time}</span>
                            </div>
                        </div>
                    </div>
                {/each}
            </div>
        </div>
    </div>
</div>

// docs/nextjs/app/admin/dashboard/page.tsx
'use client';

import { DashboardLayout } from '@/components/layout/dashboard-layout';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Icons } from '@/components/icons';
import Link from 'next/link';
import { useState, useEffect } from 'react';
import { PostsApi } from '@/services/api';

export default function DashboardPage() {
  const [isLoading, setIsLoading] = useState(true);
  const [stats, setStats] = useState({
    posts: 0,
    pages: 0,
    users: 0,
    media: 0
  });

  // Simulate loading stats
  useEffect(() => {
    const fetchStats = async () => {
      try {
        // Replace with actual API calls when available
        const postsData = await PostsApi.getPosts(0, 1);

        setStats({
          posts: postsData.data.totalItems || 0,
          pages: 12, // Mock data
          users: 5, // Mock data
          media: 24 // Mock data
        });
      } catch (error) {
        console.error('Error fetching dashboard stats:', error);
      } finally {
        setIsLoading(false);
      }
    };

    fetchStats();
  }, []);

  // Dashboard stat cards
  const statsCards = [
    {
      title: 'Total Posts',
      value: isLoading ? '...' : stats.posts,
      icon: <Icons.post className='text-muted-foreground h-4 w-4' />,
      description: 'All published and draft posts',
      href: '/admin/post'
    },
    {
      title: 'Total Pages',
      value: isLoading ? '...' : stats.pages,
      icon: <Icons.file className='text-muted-foreground h-4 w-4' />,
      description: 'All published and draft pages',
      href: '/admin/page'
    },
    {
      title: 'Registered Users',
      value: isLoading ? '...' : stats.users,
      icon: <Icons.user className='text-muted-foreground h-4 w-4' />,
      description: 'All registered users',
      href: '/admin/user'
    },
    {
      title: 'Media Items',
      value: isLoading ? '...' : stats.media,
      icon: <Icons.media className='text-muted-foreground h-4 w-4' />,
      description: 'All uploaded media files',
      href: '/admin/media'
    }
  ];

  // Quick actions
  const quickActions = [
    {
      title: 'Create New Post',
      description: 'Start writing a new blog post',
      icon: <Icons.post className='h-4 w-4' />,
      href: '/admin/post/create'
    },
    {
      title: 'Add New Page',
      description: 'Create a new website page',
      icon: <Icons.file className='h-4 w-4' />,
      href: '/admin/page/create'
    },
    {
      title: 'Upload Media',
      description: 'Add images or documents',
      icon: <Icons.media className='h-4 w-4' />,
      href: '/admin/media/upload'
    },
    {
      title: 'Manage Settings',
      description: 'Configure your website',
      icon: <Icons.settings className='h-4 w-4' />,
      href: '/admin/settings'
    }
  ];

  // Recent activity feed (mock data)
  const activityFeed = (
    <div className='space-y-4'>
      {[
        {
          user: 'admin',
          action: 'created a new post',
          time: '2 hours ago',
          type: 'post'
        },
        {
          user: 'editor',
          action: 'updated a page',
          time: '5 hours ago',
          type: 'page'
        },
        {
          user: 'admin',
          action: 'uploaded media',
          time: '1 day ago',
          type: 'media'
        },
        {
          user: 'contributor',
          action: 'commented on a post',
          time: '2 days ago',
          type: 'comment'
        }
      ].map((activity, i) => (
        <div key={i} className='flex items-start space-x-3 py-2'>
          <span className='bg-accent flex h-8 w-8 shrink-0 items-center justify-center rounded-full'>
            {activity.type === 'post' && <Icons.post className='h-4 w-4' />}
            {activity.type === 'page' && <Icons.file className='h-4 w-4' />}
            {activity.type === 'media' && <Icons.media className='h-4 w-4' />}
            {activity.type === 'comment' && <Icons.post className='h-4 w-4' />}
          </span>
          <div className='space-y-1'>
            <p className='text-sm leading-none font-medium'>
              <span className='font-semibold'>{activity.user}</span>{' '}
              {activity.action}
            </p>
            <p className='text-muted-foreground text-xs'>{activity.time}</p>
          </div>
        </div>
      ))}
    </div>
  );

  // Main content
  const mainContent = (
    <Card>
      <CardHeader>
        <CardTitle>Welcome to your Dashboard</CardTitle>
      </CardHeader>
      <CardContent>
        <p className='text-muted-foreground mb-4'>
          This is your Mixcore dashboard. Get started by creating content or
          managing your site.
        </p>
        <div className='grid gap-4 md:grid-cols-2'>
          <Link href='/admin/post/create' className='block'>
            <Button className='w-full justify-start' variant='outline'>
              <Icons.post className='mr-2 h-4 w-4' />
              Create New Post
            </Button>
          </Link>
          <Link href='/admin/page/create' className='block'>
            <Button className='w-full justify-start' variant='outline'>
              <Icons.file className='mr-2 h-4 w-4' />
              Create New Page
            </Button>
          </Link>
          <Link href='/admin/media/upload' className='block'>
            <Button className='w-full justify-start' variant='outline'>
              <Icons.media className='mr-2 h-4 w-4' />
              Upload Media
            </Button>
          </Link>
          <Link href='/admin/settings' className='block'>
            <Button className='w-full justify-start' variant='outline'>
              <Icons.settings className='mr-2 h-4 w-4' />
              Site Settings
            </Button>
          </Link>
        </div>
      </CardContent>
    </Card>
  );

  return (
    <DashboardLayout
      statsCards={statsCards}
      quickActions={quickActions}
      activityFeed={activityFeed}
      contentArea={mainContent}
    />
  );
}
