// src/src/routes/(auth)/security/login/+page.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import { goto } from "$app/navigation";
  import { page } from "$app/stores";
  import { AuthService } from "$lib/services/auth-service";
  import { isBusy, showErrors, goToSiteUrl } from "$lib/services/common";
  import type { LoginData, ExternalLoginData } from "$lib/types";
  import { Button } from "$lib/components/ui/button";
  import { Card, CardHeader, CardContent, CardFooter } from "$lib/components/ui/card";
  import { Input } from "$lib/components/ui/input";
  import { Label } from "$lib/components/ui/label";
  import { Checkbox } from "$lib/components/ui/checkbox";

  let loginData: LoginData = {
    username: "",
    password: "",
    rememberMe: true
  };

  let externalLoginData: ExternalLoginData = {
    username: "",
    email: "",
    accessToken: ""
  };

  let canLogin = true;
  let error = "";

  onMount(async () => {
    $isBusy = false;
  });

  // Function to check if the user has permissions for a given URL
  function hasPermission(url: string): boolean {
    return url === "/" || globalThis.$isAdmin || false; // Add permission check here
  }

  // Get the return URL from the query parameters or use a default
  function getReturnUrl(): string {
    const returnUrl = $page.url.searchParams.get("ReturnUrl");
    if (returnUrl) return returnUrl;

    const referrer = document.referrer;
    if (referrer && referrer.indexOf("init") === -1) {
      return referrer;
    }

    return "/";
  }

  async function handleLogin() {
    $isBusy = true;
    error = "";

    try {
      const result = await AuthService.externalLogin(externalLoginData, "providerName");

      if (result.isSucceed) {
        const returnUrl = getReturnUrl();
        window.top.location.href = returnUrl;
      } else {
        if (result.errors) {
          error = result.errors[0];
          showErrors(result.errors);
        }
      }
    } catch (err) {
      error = "An error occurred during login";
      console.error(err);
    } finally {
      $isBusy = false;
    }
  }

  async function handleExternalLogin(response: any, provider: string) {
    try {
      const result = await AuthService.externalLogin(response, provider);

      if (result) {
        canLogin = false;
        const returnUrl = getReturnUrl();

        if (hasPermission(returnUrl)) {
          window.top.location.href = returnUrl;
        } else {
          error = "You don't have permission to access this URL";
          showErrors(["You don't have permission to access this URL"]);
        }
      }
    } catch (err) {
      error = "An error occurred during external login";
      console.error(err);
    }
  }

  function logOut() {
    canLogin = true;
  }

  function handleKeyPress(event: KeyboardEvent) {
    if (event.key === "Enter") {
      handleLogin();
    }
  }
</script>

<svelte:window on:keydown={handleKeyPress} />

<div class="container-tight py-4">
  <div class="text-center m-4">
    <a href="/"><img src="/mix-app/css/portal/img/mixcore-logo-red-2.svg" alt="Mixcore CMS" height="36"></a>
  </div>

  <Card class="max-w-md mx-auto">
    <CardHeader class="text-center py-4 p-sm-5">
      <img src="/mix-app/css/portal/img/illustrations/undraw_secure_login_pdn4.svg" height="128" class="mb-2 mx-auto" alt="">
      <h1 class="mt-5 text-2xl font-bold">Portal</h1>
      <p class="text-muted-foreground">Let manage your site together!</p>
    </CardHeader>

    <div class="relative">
      <div class="absolute inset-0 flex items-center">
        <div class="w-full border-t"></div>
      </div>
      <div class="relative flex justify-center text-xs uppercase">
        <span class="bg-background px-2 text-muted-foreground">login form</span>
      </div>
    </div>

    <CardContent class="p-5">
      <form class="mb-3 space-y-4">
        {#if canLogin}
          <div>
            <Label for="username">Username</Label>
            <Input 
              id="username" 
              placeholder="Username" 
              bind:value={externalLoginData.username} 
              required
            />
          </div>

          <div>
            <Label for="email">Email</Label>
            <Input 
              id="email" 
              type="email" 
              placeholder="Email" 
              bind:value={externalLoginData.email} 
              required
            />
          </div>

          <div>
            <Label for="accessToken">Access Token</Label>
            <Input 
              id="accessToken" 
              placeholder="Access Token" 
              bind:value={externalLoginData.accessToken} 
              required
            />
          </div>
        {/if}
      </form>
    </CardContent>

    <CardFooter class="flex-col items-center space-y-4">
      <!-- External login buttons would go here -->
      <!-- <button on:click={() => externalLogin(...)} class="...">Facebook Login</button> -->

      {#if canLogin}
        <Button 
          onclick={() => handleLogin()}
          disabled={!externalLoginData.username || !externalLoginData.email || !externalLoginData.accessToken}
          class="px-5"
        >
          Login
        </Button>
      {/if}

      {#if error}
        <p class="text-destructive text-sm">{error}</p>
      {/if}

      <div class="flex space-x-2">
        <Button variant="link" onclick={() => goToSiteUrl('/')}>
          Homepage
        </Button>
        <span>|</span>
        <Button variant="link" onclick={() => goToSiteUrl('/security/register')}>
          Register
        </Button>
      </div>
    </CardFooter>
  </Card>
</div>

// docs/nextjs/app/security/login/page.tsx
'use client';

import { useState, useEffect } from 'react';
import { useRouter, useSearchParams } from 'next/navigation';
import { Formik, Form as FormikForm, Field, ErrorMessage } from 'formik';
import * as Yup from 'yup';
import { AuthService } from '@/services/auth';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Alert, AlertDescription } from '@/components/ui/alert';
import { AlertCircle } from 'lucide-react';
import { Checkbox } from '@/components/ui/checkbox';
import {
  Card,
  CardContent,
  CardHeader,
  CardTitle,
  CardDescription
} from '@/components/ui/card';

interface LoginFormValues {
  username: string;
  password: string;
  rememberMe: boolean;
}

const initialValues: LoginFormValues = {
  username: '',
  password: '',
  rememberMe: false
};

const validationSchema = Yup.object({
  username: Yup.string().required('Username is required'),
  password: Yup.string().required('Password is required'),
  rememberMe: Yup.boolean()
});

export default function Login() {
  const router = useRouter();
  const searchParams = useSearchParams();
  const [error, setError] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [externalProviders, setExternalProviders] = useState<string[]>([]);

  useEffect(() => {
    // Get external login providers
    AuthService.getExternalLoginProviders().then((providers) => {
      setExternalProviders(providers);
    });
  }, []);

  const handleSubmit = async (values: LoginFormValues) => {
    setIsLoading(true);
    setError(null);

    try {
      const result = await AuthService.login(
        values.username,
        values.password,
        values.rememberMe
      );

      if (result.success) {
        const returnUrl = searchParams.get('ReturnUrl');
        if (returnUrl) {
          router.push(returnUrl);
        } else if (document.referrer && !document.referrer.includes('init')) {
          router.push(document.referrer);
        } else {
          router.push('/admin/dashboard');
        }
      } else {
        setError(result.errors?.[0] || 'Login failed. Please try again.');
      }
    } catch {
      setError('An error occurred during login. Please try again.');
    } finally {
      setIsLoading(false);
    }
  };

  const handleExternalLogin = async (provider: string) => {
    setIsLoading(true);
    setError(null);

    try {
      // Open external login popup
      const width = 600;
      const height = 750;
      const left = window.screen.width / 2 - width / 2;
      const top = window.screen.height / 2 - height / 2;

      const popup = window.open(
        `/authcomplete.html?provider=${provider}`,
        'Authenticate Account',
        `width=${width},height=${height},left=${left},top=${top}`
      );

      // Listen for message from popup
      window.addEventListener('message', async (event) => {
        if (event.origin !== window.location.origin) return;

        const { userID, email, accessToken } = event.data;
        if (userID && email && accessToken) {
          const result = await AuthService.externalLogin({
            provider,
            username: userID,
            email,
            accessToken
          });

          if (result.success) {
            const returnUrl = searchParams.get('ReturnUrl');
            if (returnUrl) {
              router.push(returnUrl);
            } else if (
              document.referrer &&
              !document.referrer.includes('init')
            ) {
              router.push(document.referrer);
            } else {
              router.push('/admin/dashboard');
            }
          } else {
            setError(
              result.errors?.[0] || 'External login failed. Please try again.'
            );
          }
        }
      });
    } catch {
      setError('An error occurred during external login. Please try again.');
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className='container flex min-h-screen items-center justify-center px-4 py-12'>
      <div className='w-full max-w-md space-y-6'>
        <div className='flex justify-center'>
          <h1 className='text-3xl font-bold'>Mixcore</h1>
        </div>

        <Card>
          <CardHeader>
            <CardTitle className='text-center'>Login</CardTitle>
            <CardDescription className='text-center'>
              Enter your credentials to access your account
            </CardDescription>
          </CardHeader>
          <CardContent>
            {error && (
              <Alert variant='destructive' className='mb-4'>
                <AlertCircle className='h-4 w-4' />
                <AlertDescription>{error}</AlertDescription>
              </Alert>
            )}

            <Formik
              initialValues={initialValues}
              validationSchema={validationSchema}
              onSubmit={handleSubmit}
            >
              {({ values, setFieldValue }) => (
                <FormikForm className='space-y-4'>
                  <div className='space-y-2'>
                    <Label htmlFor='username'>Username</Label>
                    <Field
                      as={Input}
                      id='username'
                      name='username'
                      type='text'
                      placeholder='Enter your username'
                    />
                    <ErrorMessage
                      name='username'
                      component='div'
                      className='text-sm text-red-500'
                    />
                  </div>

                  <div className='space-y-2'>
                    <Label htmlFor='password'>Password</Label>
                    <Field
                      as={Input}
                      id='password'
                      name='password'
                      type='password'
                      placeholder='Enter your password'
                    />
                    <ErrorMessage
                      name='password'
                      component='div'
                      className='text-sm text-red-500'
                    />
                  </div>

                  <div className='flex items-center space-x-2'>
                    <Checkbox
                      id='rememberMe'
                      checked={values.rememberMe}
                      onCheckedChange={(checked) =>
                        setFieldValue('rememberMe', checked)
                      }
                    />
                    <Label htmlFor='rememberMe'>Remember me</Label>
                  </div>

                  <Button type='submit' className='w-full' disabled={isLoading}>
                    {isLoading ? 'Logging in...' : 'Login'}
                  </Button>
                </FormikForm>
              )}
            </Formik>

            {externalProviders.length > 0 && (
              <div className='mt-6'>
                <div className='relative'>
                  <div className='absolute inset-0 flex items-center'>
                    <div className='w-full border-t border-gray-300' />
                  </div>
                  <div className='relative flex justify-center text-sm'>
                    <span className='bg-white px-2 text-gray-500'>
                      Or continue with
                    </span>
                  </div>
                </div>

                <div className='mt-6 grid grid-cols-2 gap-3'>
                  {externalProviders.map((provider) => (
                    <Button
                      key={provider}
                      variant='outline'
                      className='w-full'
                      onClick={() => handleExternalLogin(provider)}
                      disabled={isLoading}
                    >
                      {provider}
                    </Button>
                  ))}
                </div>
              </div>
            )}
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
